// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi8AX-WK8CBq7kMB6UHNAIkKrN04lVb3M',
    appId: '1:1010266950422:web:673df231b3e085244c9e37',
    messagingSenderId: '1010266950422',
    projectId: 'reading-memo-67bb8',
    authDomain: 'reading-memo-67bb8.firebaseapp.com',
    storageBucket: 'reading-memo-67bb8.appspot.com',
    measurementId: 'G-WFJMK9HVWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoXrcTHCz4lSquu9Xdr_Dd5uw7jYqB-K8',
    appId: '1:1010266950422:android:7fdef2f11e6bea0d4c9e37',
    messagingSenderId: '1010266950422',
    projectId: 'reading-memo-67bb8',
    storageBucket: 'reading-memo-67bb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_f0KSDt6pNXyyctnR8ZGMWSrQFU57Xnc',
    appId: '1:1010266950422:ios:5611b17b3c1253d04c9e37',
    messagingSenderId: '1010266950422',
    projectId: 'reading-memo-67bb8',
    storageBucket: 'reading-memo-67bb8.appspot.com',
    iosClientId: '1010266950422-30i33aqtnm63j653afg700hig46gerod.apps.googleusercontent.com',
    iosBundleId: 'com.example.readingMemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_f0KSDt6pNXyyctnR8ZGMWSrQFU57Xnc',
    appId: '1:1010266950422:ios:32aa5c78fd0879114c9e37',
    messagingSenderId: '1010266950422',
    projectId: 'reading-memo-67bb8',
    storageBucket: 'reading-memo-67bb8.appspot.com',
    iosClientId: '1010266950422-6tf0gin8f4i65slcre06lhpd6abmhnkd.apps.googleusercontent.com',
    iosBundleId: 'com.example.readingMemo.RunnerTests',
  );
}
